sudo: required
dist: trusty
services:
  - mongodb

language: python

mongodb:
  - 3.4

python:
  - 3.5
  - 3.6
  - 'nightly'

os:
  - linux

matrix:
  allow_failures:
    - python: 'nightly'

cache:
  directories:
    - $HOME/.cache/pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

install:
  - pip install --upgrade pip wheel
  - pip install --upgrade setuptools
  - pip install -r dev-requirements.txt

script:
  - py.test ./tests
