sudo: false
dist: precise

language: python

python:
  - 3.5
  - 3.6
  - 'nightly'

addons:
  apt:
    sources:
    - mongodb-3.4-precise
    packages:
    - mongodb-org

os:
  - linux

matrix:
  allow_failures:
    - python: 'nightly'

cache:
  directories:
    - $HOME/.cache/pip

before_script:
  - mongo --version

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

install:
  - pip install --upgrade pip wheel
  - pip install --upgrade setuptools
  - pip install -r dev-requirements.txt

script:
  - py.test ./tests
