version: '3.1'

services:
   db:
     image: mongo:3.4
     networks:
      - aiomongo

   tests:
     build:
       context: .
     image: aiomongo
     command: py.test -s -vv /opt/project/tests
     container_name: aiomongo
     volumes:
       - .:/opt/project
     depends_on:
       - db
     working_dir: /opt/project
     environment:
       - MONGO_HOST=db
       - PYTHONPATH=/opt/project
     networks:
       - aiomongo

   aiomongo_run:
     build:
       context: .
     image: aiomongo
     command: python run.py
     volumes:
       - .:/opt/project
     working_dir: /opt/project
     environment:
       - PYTHONPATH=/opt/project

   benchmarks:
     build:
       context: .
     image: aiomongo
     command: bash -c "py.test ./benchmark --benchmark-json=benchmark.json --benchmark-warmup=on --benchmark-warmup-iterations=10 && python ./benchmark/plotbench.py"
     container_name: aiomongo
     volumes:
       - .:/opt/project
     depends_on:
       - db
     working_dir: /opt/project
     environment:
       - MONGO_HOST=db
       - PYTHONPATH=/opt/project
     networks:
       - aiomongo


networks:
  aiomongo:
    driver: bridge
